<?php

/**
 * @file
 * Module definition
 */

define('AUTH0_DEFAULT_SCOPES', 'openid email profile');
define('AUTH0_DEFAULT_SIGNING_ALGORITHM', 'RS256');
define('AUTH0_DEFAULT_USERNAME_CLAIM', 'nickname');

/**
 * Replace a form with the lock widget.
 */
function auth0_theme() {
  return array(
    'auth0_login' => array(
      'template' => 'auth0-login',
      'variables' => array(
        'domain' => NULL,
        'clientID' => NULL,
        'state' => NULL,
        'showSignup' => NULL,
        'offlineAccess' => FALSE,
        'widgetCdn' => NULL,
        'loginCSS' => NULL,
        'callbackURL' => NULL,
        'lockExtraSettings' => '{}',
        'scopes' => AUTH0_DEFAULT_SCOPES,
      ),
    ),
  );
}

/**
 * Handle users deletion, it should delete the Auth0 profile.
 */
function auth0_user_delete($account) {
  db_delete('auth0_user')
    ->condition('drupal_id', $account->uid->value)
    ->execute();
}

/**
 * Use Refresh Token.
 */
function auth0_signin_with_refresh_token($token) {
  $helper = \Drupal::service('auth0.helper');

  return $helper->getUserUsingRefreshToken($token);
}
