<?php

/**
 * Replace a form with the lock widget.
 */
function auth0_theme() {

  global $base_root;
  
  return array(
    'auth0_login' => array(
      'template' => 'auth0-login',
      'variables' => array(
        'domain' => null,
        'clientID' => null,
        'state' => null,
        'showSignup' => null,
        'widgetCdn' => null,
        'loginCSS' => null,
        'callbackURL' => null,
        'lockExtraSettings' => '{}',
      ),
    ),
  );
}

function auth0_user_delete($account) {
  db_delete('auth0_user')
    ->condition('drupal_id', $account->uid->value)
    ->execute();
}