<?php
// Create a variable to store the path to this module
define('AUTH0_PATH', drupal_get_path('module', 'auth0'));

/**
 * Implements hook_theme
 * Define the template to use for the /user action
 */
function auth0_theme() {

  global $base_root;
  
  return array(
    'auth0_login' => array(
      'template' => 'auth0-login',
      'variables' => array(
        'domain' => null,
        'clientID' => null,
        'state' => null,
        'showSignup' => null,
        'widgetCdn' => null,
        'loginCSS' => null,
        'callbackURL' => null,
        'lockExtraSettings' => '{}',
      ),
    ),
  );
}

function auth0_user_delete($account) {
  db_delete('auth0_user')
    ->condition('drupal_id', $account->uid->value)
    ->execute();
}